docker stop $(imageName)
docker rm $(imageName)
docker rm -f $(docker ps -a |  grep "$(imageName)*"  | awk '{print $1}')
docker pull $(dockerId)/$(imageName):$(Build.BuildNumber)
docker run -d -p 5000:80 --restart=always --name $(imageName) $(dockerId)/$(imageName):$(Build.BuildNumber) GitUrl=$(GitUrl) GitUid=$(GitUid) GitPWD=$(GitPWD)