docker pull $DOCKERID/$IMAGENAME:$BUILD_BUILDNUMBER
docker stop $IMAGENAME
docker rm $IMAGENAME
docker run -d -p 5000:5000 --restart=always --name $IMAGENAME $DOCKERID/$IMAGENAME:$BUILD_BUILDNUMBER DbServer=$DBSERVER DbName=$DBNAME DbUID=$DBUID DbPWD=$DB_PWD BuildNumber=$BUILD_BUILDNUMBER RedisConStr=$REDISCONSTR RabbitMqHost=$RABBITMQHOST RabbitMqPWD=$RABBITMQPWD RabbitMqUID=$RABBITMQUID